# Generated by Django 3.0.8 on 2023-02-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_employer',
            field=models.BooleanField(default=False, verbose_name='employer status'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_worker',
            field=models.BooleanField(default=False, verbose_name='worker status'),
        ),
    ]
